### ISSUE TITLE
Getting MapPoint producing error. 

### ISSUE THREAD

**Issue by reachomk** [AtlisInc/Nominatim-API#9]
Hello, I am receiving the following error with the following method. Is this a bug with the code, and if not, how would I avoid this?

Code:     

private void showContacts() {
        String endpointUrl = "https://nominatim.openstreetmap.org/";
        for(Contact c: contactList) {
            Address address = c.getAddress();
            MapPoint mapPoint = NominatimAPI.with(endpointUrl).getMapPointFromAddress(address, 5);
            Log.e(c.getName(), mapPoint.toString());
        }
    }

Error: 

java.lang.BootstrapMethodError: Exception from call site #30 bootstrap method
        at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
        at org.apache.commons.lang3.builder.ReflectionToStringBuilder.checkNotNull(ReflectionToStringBuilder.java:437)
        at org.apache.commons.lang3.builder.ReflectionToStringBuilder.<init>(ReflectionToStringBuilder.java:553)
        at org.apache.commons.lang3.builder.ReflectionToStringBuilder.toString(ReflectionToStringBuilder.java:311)
        at org.apache.commons.lang3.builder.ReflectionToStringBuilder.toString(ReflectionToStringBuilder.java:130)
        at org.apache.commons.lang3.builder.ToStringBuilder.reflectionToString(ToStringBuilder.java:149)
        at com.atlis.location.model.LocationModelAbs.toString(LocationModelAbs.java:18)
        at java.lang.String.valueOf(String.java:2896)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at com.atlis.location.nominatim.NominatimAPI.getMapPointFromAddress(NominatimAPI.java:155)
        at com.atlis.location.nominatim.NominatimAPI.getMapPointFromAddress(NominatimAPI.java:137)
        at com.reachomk.contacthome.MapsActivity.showContacts(MapsActivity.java:232)
        at com.reachomk.contacthome.MapsActivity.getContacts(MapsActivity.java:225)
        at com.reachomk.contacthome.MapsActivity.onMapReady(MapsActivity.java:95)
        at com.google.android.gms.maps.zzak.zza(Unknown Source:2)
        at com.google.android.gms.maps.internal.zzaq.dispatchTransaction(Unknown Source:12)
        at com.google.android.gms.internal.maps.zzb.onTransact(Unknown Source:12)
        at android.os.Binder.transact(Binder.java:667)
        at dc.b(:com.google.android.gms.dynamite_mapsdynamite@202117068@20.21.17 (100700-0):2)
        at com.google.maps.api.android.lib6.impl.be.run(:com.google.android.gms.dynamite_mapsdynamite@202117068@20.21.17 (100700-0):2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at org.apache.commons.lang3.Validate.notNull(Validate.java:225) 
        at org.apache.commons.lang3.builder.ReflectionToStringBuilder.checkNotNull(ReflectionToStringBuilder.java:437) 
        at org.apache.commons.lang3.builder.ReflectionToStringBuilder.<init>(ReflectionToStringBuilder.java:553) 
        at org.apache.commons.lang3.builder.ReflectionToStringBuilder.toString(ReflectionToStringBuilder.java:311) 
        at org.apache.commons.lang3.builder.ReflectionToStringBuilder.toString(ReflectionToStringBuilder.java:130) 
        at org.apache.commons.lang3.builder.ToStringBuilder.reflectionToString(ToStringBuilder.java:149) 
        at com.atlis.location.model.LocationModelAbs.toString(LocationModelAbs.java:18) 
        at java.lang.String.valueOf(String.java:2896) 
        at java.lang.StringBuilder.append(StringBuilder.java:132) 
        at com.atlis.location.nominatim.NominatimAPI.getMapPointFromAddress(NominatimAPI.java:155) 
        at com.atlis.location.nominatim.NominatimAPI.getMapPointFromAddress(NominatimAPI.java:137) 
        at com.reachomk.contacthome.MapsActivity.showContacts(MapsActivity.java:232) 
        at com.reachomk.contacthome.MapsActivity.getContacts(MapsActivity.java:225) 
        at com.reachomk.contacthome.MapsActivity.onMapReady(MapsActivity.java:95) 
        at com.google.android.gms.maps.zzak.zza(Unknown Source:2) 
        at com.google.android.gms.maps.internal.zzaq.dispatchTransaction(Unknown Source:12) 
        at com.google.android.gms.internal.maps.zzb.onTransact(Unknown Source:12) 
        at android.os.Binder.transact(Binder.java:667) 
        at dc.b(:com.google.android.gms.dynamite_mapsdynamite@202117068@20.21.17 (100700-0):2) 
        at com.google.maps.api.android.lib6.impl.be.run(:com.google.android.gms.dynamite_mapsdynamite@202117068@20.21.17 (100700-0):2) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by michaelassraf** [comment]
Any chance you have a different commons-lang3?

**Comment by reachomk** [comment]
I'm using this. 

implementation 'org.apache.commons:commons-lang3:3.10'

**Comment by reachomk** [comment]
Fixed issue - if someone is using android they need to add this to their build.gradle 

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
